const useDrQualifications = () => {
    const qualifications = [
        "FCPS, MD, DEG29",
        "FCPS, DEG7",
        "MD, DEG15",
        "MBBS, DDV, DEG19",
        "DDV, DEG40",
        "B.Sc, NDEG41",
        "BAMS, NDEG36",
        "BCS, DEG10",
        "BDA, NDEG21",
        "BDS, DEG2",
        "BDS, PGT, DEG18",
        "BHMS, NDEG9",
        "BHS, NDEG27",
        "BMIDT, NDEG16",
        "BPT, NDEG40",
        "BRMP, NDEG15",
        "CCD, DEG37",
        "DA, DEG39",
        "DCARD, DEG14",
        "DCC, NDEG38",
        "DCH, DEG38",
        "DD, DEG36",
        "DDT, NDEG10",
        "DEM, DEG41",
        "DGO, DEG9",
        "DHMS, NDEG18",
        "DIDDT, NDEG12",
        "DLO, DEG16",
        "DMA, NDEG6",
        "DMF, NDEG2",
        "DMRT, DEG44",
        "DMS, NDEG24",
        "DMS, DEG27",
        "DMT, NDEG2O",
        "DMT, NDEG20",
        "DMTD, NDEG31",
        "DO, DEG25",
        "DORTHO, DEG13",
        "DPM, NDEG28",
        "DPM, DEG26",
        "DTCD, DEG17",
        "DTP, DEG35",
        "FPCIC, NDEG35",
        "FRCS, DEG24",
        "HMFC, NDEG17",
        "LLMP, NDEG23",
        "LMAF, NDEG25",
        "LMAFP, NDEG3",
        "LMF, NDEG4",
        "LMP, NDEG32",
        "M.Phil., DEG12",
        "M.Sc, NDEG42",
        "M.Sc, NDEG42",
        "MBBS, MBBS",
        "MBBS, MBBS",
        "MBBS, DEG1",
        "MBBS, BCS, DEG11",
        "MBBS, CCD, DEG3",
        "MBBS, DCH, DEG4",
        "MBBS, FCPS, DEG5",
        "MBBS, PGT, DEG6",
        "MBBS, PGT, DEG6",
        "MBVB, NDEG34",
        "MCPS, DEG20",
        "MFPC, NDEG33",
        "MPH, DEG43",
        "MRCP, DEG22",
        "MRD, NDEG26",
        "MS, DEG8",
        "OCDS, NDEG19",
        "OCDS, NDEG19",
        "PGT, DEG23",
        "PHCP, NDEG7",
        "PMAF, NDEG37",
        "Ph.D, DEG42",
        "RMP, NDEG1",
        "RPM, NDEG22",
        "SDM, NDEG11",
        "THA, DEG21",
        "TPD, NDEG14",
        "VDRMP, NDEG29"
    ];

    return [qualifications];
};

export default useDrQualifications;