const useDrDesignations = () => {
    const designations = [
        "ASSISTANT DIRECTOR, DEG17",
        "ASSISTANT PROFESSOR, DEG1",
        "ASSISTANT REGISTRAR, DEG18",
        "ASSISTANT SURGEON, DEG19",
        "ASSOCIATE PROFESSOR, DEG2",
        "BRIGADIER GENERAL, DEG26",
        "CHIEF MEDICAL OFFICER, DEG38",
        "CIVIL SURGEON, DEG20",
        "COLONEL, DEG45",
        "CONSULTANT, DEG3",
        "DENTIST, DEG21",
        "DEPUTY DIRECTOR, DEG16",
        "DIRECTOR, DEG15",
        "Doctor Cum Chemist, DEG5",
        "EMO, DEG22",
        "GENERAL PRACTITIONER, DEG41",
        "IMO, DEG39",
        "INTERN, DEG23",
        "JUNIOR CONSULTANT, DEG24",
        "LIEUTENANT COLONEL, DEG",
        "Lecturer, DEG7",
        "MAJOR, DEG46",
        "MAJOR GENERAL, DEG49",
        "MANAGING DIRECTOR, DEG14",
        "MEDICAL ASSISTANT, DEG27",
        "MEDICAL DIRECTOR, DEG43",
        "MEDICAL OFFICER, DEG8",
        "MEDICAL TECHNOLOGIST, DEG28",
        "NULL, DEG50",
        "PC, DEG44",
        "PRINCIPAL, DEG29",
        "PRO VC, DEG48",
        "PROFESSOR, DEG9",
        "PROFESSOR AND PRINCIPAL, DEG30",
        "REGISTRAR, DEG31",
        "RESIDENTIAL MEDICAL OFFICER, DEG32",
        "RESIDENTIAL PHYSICIAN, DEG33",
        "RESIDENTIAL SURGEON, DEG34",
        "SACMO, DEG35",
        "SAUHC, DEG40",
        "SENIOR CONSULTANT, DEG36",
        "SENIOR MEDICAL OFFICER, DEG42",
        "SUPERINTENDENT, DEG37",
        "Thana Health Assistant, DEG12",
        "Upazila Health & Family Planning Officer, DEG13",
        "VC, DEG47"
    ];

    return [designations];
};

export default useDrDesignations;